{%- from "devops_portal/map.jinja" import config with context %}
{%- from "devops_portal/map.jinja" import setup with context %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-portal
    spec:
      containers:
        - name: nginx
          image: {{ setup.kubernetes.image }}
          env:
            - name: CONFIGMAP_HASH
              value: {{ salt['hashutil.digest_file'](config.base_dir + '/kubernetes/devops_portal-cm.yaml') }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/config
              readOnly: true
            - name: config-json
              mountPath: /opt/devops-portal/config
              readOnly: true
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: nginx-conf
          configMap:
            name: devops-portal
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: config-json
          configMap:
            name: devops-portal
            items:
              - key: config.json
                path: config.json
      restartPolicy: Always
