{%- from "devops_portal/map.jinja" import setup with context %}
apiVersion: v1
kind: Service
metadata:
  name: devops-portal
spec:
  selector:
    app: devops-portal
  ports:
    - name: http
      protocol: TCP
      port: {{ setup.kubernetes.external_port }}
      targetPort: 8000
  externalIPs:
    - {{ setup.kubernetes.external_ip }}
