{%- macro include_by_filename(filename) -%}
  {%- include filename -%}
{%- endmacro -%}
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-portal
data:
  config.json: |
{{ include_by_filename('/srv/oss/devops_portal/config/config.json')|indent(width=4, indentfirst=True) }}
  nginx.conf: |
{{ include_by_filename('/srv/oss/devops_portal/nginx/nginx.conf')|indent(width=4, indentfirst=True) }}
