{%- from "devops_portal/map.jinja" import config with context %}
{%- set container = config.container %}
apiVersion: v1
kind: Service
metadata:
  name: devops-portal
spec:
  selector:
    app: devops-portal
  ports:
    - name: http
      protocol: TCP
      port: {{ container.external_port }}
      targetPort: {{ container.container_port }}
  externalIPs:
    - {{ container.external_ip }}
